[package]
name = "actix-diesel"
version = "0.0.0"
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.3.3", features = [ "r2d2" ] }
actix = "0.7.9"
num_cpus = "1.9.0"
once_cell = "0.1.6"
futures = "0.1.25"
derive_more = "0.13.0"
r2d2 = "0.8.3"
actix-web = { version = "0.7.17", optional = true }

[patch.crates-io]
# https://github.com/tokio-rs/tokio/pull/814
tokio-async-await = { git = "https://github.com/balthild/tokio", rev = "f00a9ab24c948c6c5c7a769eb894480faa425866" }
